FROM fopina/fluent-bit-plugin-dev:v1.9.2-2 as builder

RUN apt update && apt install -y libc-ares-dev

ADD . /myplugin

RUN cmake -DFLB_SOURCE=/usr/src/fluentbit/fluent-bit-1.9.2/ \
          -DPLUGIN_NAME=filter_lua2 \
          ../

RUN make

RUN ls -la

FROM scratch

COPY --from=builder /myplugin/build/flb-filter_lua2.so /
